/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import DAO.DatoDAO;
import Datos.Historico;
import Entidad.Sensor;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class Mostrar extends javax.swing.JPanel {
    DatoDAO dao=new DatoDAO();
    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabla = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        SensorId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.setViewportView(TablaDatos);

        jButton1.setText("MostrarDatos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostraAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SensorId, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SensorId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addComponent(Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MostraAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostraAction
        int id;
        ArrayList<Historico> h;
        Sensor sensor;
        try{
            id=Integer.parseInt(SensorId.getText().toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese valores numericos solamente porfavor","Corrija sus errores",JOptionPane.ERROR_MESSAGE);
            return;
        }
        sensor=dao.leerSensor(id);
        Object [][]object;
        String [] Titulos={"ID SENSOR","VALOR TOMADO","FECHA Y HORA DE TOMA"};
        
        if(sensor==null){
            JOptionPane.showMessageDialog(null, "El id no se encuentra en la base, intentelo nuevamente","Corrija sus errores",JOptionPane.WARNING_MESSAGE);
            
        }else{
            
            h=dao.listarPorSensor(sensor);
            if(h.size()>0){
            object=new Object[5][3];
            
            for(int i=0;i<h.size();i++){
                Date date=h.get(i).getFecha_y_hora();
                String fecha=date.getDay()+"/"+date.getMonth()+"/"+date.getYear()+"    "+date.getHours()+":"+date.getMinutes();
                object[i][0]=h.get(i).getSensor().getId();
                object[i][1]=h.get(i).getValor();
                //object[i][2]=h.get(i).getFecha_y_hora().toString();
                object[i][2]=fecha;
            }
            
            }else{
                object=new Object [][] {
                    {null, null, null},
                    {null, null, null},
                    {null, null, null}
                };
            }
            
            TablaDatos.setModel(new javax.swing.table.DefaultTableModel(object,Titulos));
        }
        
        
        
        
        
        
    }//GEN-LAST:event_MostraAction

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SensorId;
    private javax.swing.JScrollPane Tabla;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JTable getTabla(){
        return this.TablaDatos;
    }
}
